### PR TITLE
added GoSec Security Scanner on master push and pull_reqests

### PR DESCRIPTION
**Pull request by jlogelin**

### CODE REVIEW

**Review by en0ma — APPROVED** [review]

**Review by gmelodie — APPROVED** [review]

**Comment by jlogelin** [comment]
This is a bit of recursive PR ( or at least a PR with a hidden second part ). Though the pipeline code works great, it uncovers [127 potential security](https://github.com/application-research/estuary/runs/7095139639?check_suite_focus=true) issues in the codebase. *cracks knuckles*

**Comment by mvjq** [comment]
@jlogelin  are you working on these security issues?  if not, I'll be looking into it

**Comment by jlogelin** [comment]
@mvjq perfect! I haven't been able to roll back around to this lately. Please do take it.

**Comment by mvjq** [comment]
Update: Sorry for taking too much time. I did the fixes, as soon as i have free time, i'll open/write the PR, thanks!

**Comment by mvjq** [comment]
(sorry about opening another PR) PR: https://github.com/application-research/estuary/pull/362

**Comment by en0ma** [comment]
@jlogelin I think you can close this now

**Pull request closed without merging**
