### PR TITLE
increase rate limit

### PR DESCRIPTION
**Pull request by anjor**
rclone integration tests getting 429ed

### CODE REVIEW

**Comment by neelvirdy** [comment]
@anjor you probably want to do this in shuttle.go too. also curious if we know that 200 is the test requirement or if we are just 10x'ing because we have reason to believe it's much too low

**Comment by anjor** [comment]
It was the test requirement. I tested it locally.

**Comment by anjor** [comment]
It was the test requirement. I tested it locally.

**Comment by LucRoy** [comment]
This is the default value right? You can still override this with `rate-limiter` params right? Just for my knowledge :)

**Comment by anjor** [comment]
Correct.

**Comment by anjor** [comment]
The build is failing because dev is broken, not because of the changes made in this PR.

**Review by en0ma — APPROVED** [review]

**Pull request merged**
