### PR TITLE
Fix swagger anotation

### PR DESCRIPTION
**Pull request by gmelodie**

### CODE REVIEW

**Comment by alvin-reyes** [comment]
Let’s add a verification on this please. Show that the endpoint docs and 1 simple test.

**Review by en0ma — APPROVED** [review]
LGTM

**Comment by alvin-reyes** [comment]
Please resolve the conflicts and merge after.

**Review by alvin-reyes — CHANGES_REQUESTED** [review]
Fix the conflicts and merge

**Comment by gmelodie** [comment]
These changes were merged in https://github.com/application-research/estuary/pull/514

**Pull request closed without merging**
