### PR TITLE
change name variables to filename

### LINKED ISSUE #262: Change "name" field to "filename" in the Content struct
Mostly a self reminder since I don't have bandwidth to do this just about now. Just rename the field and fix everywhere it breaks.

### PR DESCRIPTION
**Pull request by gmelodie**
Fixes #262

### CODE REVIEW

**Review by alvin-reyes — COMMENTED** [review]
Thanks for this. Please add a few verification steps on this PR.

**Comment by gmelodie** [comment]
@alvin-reyes can you clarify what you mean with verification steps? Do you mean unit tests? If so, what should I unit test specifically?

**Comment by alvin-reyes** [comment]
> @alvin-reyes can you clarify what you mean with verification steps? Do you mean unit tests? If so, what should I unit test specifically?

Just test the endpoints and show that its accepting the new name and returns (response) the new name.

one example is the `/content/create` that accepts a `var req util.ContentCreateBody` which includes the `filename`. This technically means anyone who uses the `/content/create` needs to use `filename` instead of `name` which makes this a breaking API change.

image

image

We need to make sure verify if this work as is (add it to this PR) and also modify the docs with this new param.

**Comment by alvin-reyes** [comment]
# Verification
## Name column on the content table
image

## Run /content/create
image

image

**Comment by en0ma** [comment]
@alvin-reyes @gmelodie those this change require any UI updates?

**Comment by gmelodie** [comment]
@en0ma the API changes are on `/content/add` (it returns the `Content`, which now uses `Filename` instead of `Name`), `createContent` and `shuttleCreateContent`. I am not 100% sure how these last two are used

**Comment by alvin-reyes** [comment]
> @alvin-reyes @gmelodie those this change require any UI updates?

Yes. I'll have a PR that will have this change on `estuary-www` shortly.

**Review by alvin-reyes — DISMISSED** [review]
LGTM

**Review by alvin-reyes — APPROVED** [review]
LGTM

**Pull request merged**
