### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by cindywu**
Fixes typo in README where succesfully was missing an s.

### CODE REVIEW

**Comment by snissn** [comment]
lgtm

**Comment by snissn** [comment]
@alvin-reyes do we want this PR set up to dev not to master?  tysm

**Comment by alvin-reyes** [comment]
We can put it straight to `master` but let's make sure to rebase `dev` with this new change. For minor changes like docs, readme, it's ok to push to master as long as we (Estuary team) rebase `dev` with it.

**Review by snissn — APPROVED** [review]
looks great!

**Review by alvin-reyes — APPROVED** [review]
LGTM

**Pull request merged**
