### PR TITLE
chore: added default peers based on content provider list

### PR DESCRIPTION
**Pull request by alvin-reyes**
# Changes

Added all default content provider list based here https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list

# Verification
image
image

### CODE REVIEW

**Comment by en0ma** [comment]
@alvin-reyes I thought these were added as cli config values when standing estuary

**Comment by en0ma** [comment]
> > @alvin-reyes I thought these were added as cli config values when standing estuary
> 
> Not all. We only add a few from the list.
> 
> This PR will force estuary to peer with these providers upon startup.

ok, so we are treating these as a kinda bootstrap peers and any others via the cli are additions

**Comment by en0ma** [comment]
> > > > @alvin-reyes I thought these were added as cli config values when standing estuary
> > > 
> > > 
> > > Not all. We only add a few from the list.
> > > This PR will force estuary to peer with these providers upon startup.
> > 
> > 
> > ok, so we are treating these as a kinda bootstrap peers and any others via the cli are additions
> 
> Yes. This is sort of an official list that's recognized by IPFS ecosystem https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list
> 
> I'm thinking of adding a json file on [ipfs-docs](https://github.com/ipfs/ipfs-docs) repo to make it easy for anyone to consume the peers from an external source.

Hmm, that will be a hard dependency on the availability of that endpoint - not sure that is a good idea

**Review by en0ma — APPROVED** [review]
LGTM

**Comment by alvin-reyes** [comment]
> > > > > @alvin-reyes I thought these were added as cli config values when standing estuary
> > > > 
> > > > 
> > > > Not all. We only add a few from the list.
> > > > This PR will force estuary to peer with these providers upon startup.
> > > 
> > > 
> > > ok, so we are treating these as a kinda bootstrap peers and any others via the cli are additions
> > 
> > 
> > Yes. This is sort of an official list that's recognized by IPFS ecosystem https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list
> > I'm thinking of adding a json file on [ipfs-docs](https://github.com/ipfs/ipfs-docs) repo to make it easy for anyone to consume the peers from an external source.
> 
> Hmm, that will be a hard dependency on the availability of that endpoint - not sure that is a good idea

The idea is to make this json file part of the documentation. not sure if ipfs-doc team will agree but it’ll be good to just source this from a external list rather than hard coding it in our code.

**Pull request merged**
