### PR TITLE
fix&chore: bump go-car/v2 to fix missing dep issue and bump verifcid & multihash for blake3 & go-blockservice to fix double put

### PR DESCRIPTION
**Pull request by Jorropo**
## fix: update go-car to use newer release

It used to point to a floating commit that github likely GCed:
```console
$ export GOPROXY=direct # don't just download things from google's proxy
$ go mod download
go: github.com/ipld/go-car/v2@v2.1.2-0.20220124154420-9c7956a6eb9d: invalid version: unknown revision 9c7956a6eb9d
```
----
## feat: add support for blake3 blocks

We are shipping blake3 support in Kubo 0.15.0, this allows to follow this update.

### CODE REVIEW

**Comment by Jorropo** [comment]
NVM there is LOTS of things to bump.

I see you are farther behind than I expected.

**Comment by Jorropo** [comment]
I'll retry once #393 is merged

**Comment by alvin-reyes** [comment]
> I'll retry once #393 is merged

Hi @Jorropo 

We recently put up a branching strategy for our changes and we now require any features or fixes to be staged on the dev branch before we deploy. Can you please re-create a PR for this that points to `dev` branch and close this one after?

**Comment by alvin-reyes** [comment]
I added your bumps to my PR @Jorropo. I think we can close this one now.

https://github.com/application-research/estuary/pull/413

**Pull request closed without merging**
