### PR TITLE
Document content/add response structure

### PR DESCRIPTION
**Pull request by RangerMauve**
I've added the structure to the docs.go file, but I'm not sure how the JSON and Swagger are supposed to get generated.

Is this the correct approach?

I might submit one for add-car in a bit too.

### CODE REVIEW

**Comment by alvin-reyes** [comment]
docs.go is autogenerated based on the swagger annotations on the endpoints. Please check first if you can add this response structure on the main definition (top part of handler.go) first.

**Review by alvin-reyes — CHANGES_REQUESTED** [review]
Please add the documentation on the code (annotation).

**Comment by gmelodie** [comment]
Same comment as @alvin-reyes's: you need to annotate the handler function on `handlers.go` with something like:
```golang
// @Success 200 {object} MyResponseObject
```
Where `MyResponseObject` is a struct already defined and annotated as [here](https://github.com/swaggo/swag#user-defined-structure-with-an-array-type)

**Comment by RangerMauve** [comment]
Is this syntax accurate? I'm not sure how it interacts with types from other packages. 😅

**Comment by gmelodie** [comment]
@RangerMauve I think that's the right way of doing it, but @alvin-reyes there seems to be a bug where the responses never get shown on the swagger pages (see image below). Any idea what that is? I did some digging but couldn't find anything  
image

**Comment by RangerMauve** [comment]
Yeah I think I noticed that too about responses. 😅 I found that the swagger docs were nice for finding what paths exist for the API, but ultimately I had to dig into the source code to actually use anything.

**Comment by alvin-reyes** [comment]
I think there is a bug on the parses. The /pinning/pins has the failure responses [here](https://docs.estuary.tech/swagger-ui-page#/pinning/get_pinning_pins).

**Comment by alvin-reyes** [comment]
Try putting the @success annotation after @Produce or @Param but before the @Router.

**Comment by RangerMauve** [comment]
> Try putting the @success annotation after https://github.com/produce or @param but before the @router.

Like this?

**Review by gmelodie — APPROVED** [review]

**Pull request merged**
