### PR TITLE
fix collections duplicate content bug

### PR DESCRIPTION
**Pull request by en0ma**
closes https://github.com/application-research/estuary/issues/699

### CODE REVIEW

**Comment by anjor** [comment]
Test:

Before:

**Comment by en0ma** [comment]
> If you only look for `/dir1/dir2` it doesn't show `a`, I would expect there to be a `/dir1/dir2/a` entry here as well, no?:

yeah

**Comment by en0ma** [comment]
@anjor I have addressed it, and tested it;
- tested dir path that contains dir and file - works
- tested dir path that contains only file - works
- direct file path - works
- none existing/empty path - works (returns empty array now instead of null)

**Comment by en0ma** [comment]
closing this for https://github.com/application-research/estuary/pull/705

**Pull request closed without merging**
