### PR TITLE
Adding Readme for Benchest and error information for file handles open

### PR DESCRIPTION
**Pull request by aronchick**

### CODE REVIEW

**Comment by aronchick** [comment]
Adding some basic test frameworks and reorganization.

**Review by marshall — CHANGES_REQUESTED** [review]
looks great. I really appreciate the accompanying tests and docs!

I left two minor comments to address, other than that this looks good for landing to me!

**Review by aronchick — COMMENTED** [review]
Corrected some changes

**Comment by jimmylee** [comment]
LGTM

**Pull request merged**
