### PR TITLE
feat: add DealUUID to logs

### PR DESCRIPTION
**Pull request by jcace**
related: https://github.com/application-research/estuary-www/pull/96

Update `replication.go` to log out the Deal UUID in the event of a deal failure

### CODE REVIEW

**Review by jlogelin — APPROVED** [review]
LGTM

**Review by alvin-reyes — APPROVED** [review]
LGTM

**Comment by en0ma** [comment]
@alvin-reyes this was to master instead of dev

**Comment by alvin-reyes** [comment]
Yes this was intended to go to ‘dev’. We can just sync to dev.

**Pull request merged**
