### PR TITLE
Add shuttle and estuary config endpoint

### PR DESCRIPTION
**Pull request by en0ma**
This PR brings support to show the configs powering a running estuary and shuttle instances (context: https://filecoinproject.slack.com/archives/C016APFREQK/p1653085675422629). The endpoint can be accessed directly via a shuttle instance or an estuary instance. When accessed via an estuary instance, it shows the config of the estuary instance and the config of all shuttles connected to that estuary instance.

```
GET <estuary host>/admin/system/config
GET <shuttle host>/admin/system/config
```
Both endpoints require a valid estuary token with an admin-level privilege.

Sample output when accessed from an Estuary instance:

```json

"data": {
        "primary": {
            "database_conn_string": "sqlite=estuary.db",
            "staging_data_dir": "../dump/stagingdata",
            "server_cache_dir": "../dump/cache",
            "data_dir": "../dump",
            "api_listen": ":3004",
            "enable_autoretrieve": false,
            "lightstep_token": "",
            "hostname": "http://localhost:3004",
            "node": {
                "listen_addrs": [
                    "/ip4/0.0.0.0/tcp/6744"
                ],
                "announce_addrs": null,
                "enable_websocket_listen_addr": false,
                "blockstore": "../dump/estuary-blocks",
                "write_log_dir": "",
                "hard_flush_write_log": false,
                "write_log_truncate": false,
                "no_blockstore_cache": false,
                "no_limiter": true,
                "libp2p_key_file": "../dump/estuary-peer.key",
                "datastore_dir": "../dump/estuary-leveldb",
                "wallet_dir": "../dump/estuary-wallet",
                "bitswap": {
                    "max_outstanding_bytes_per_peer": 5242880,
                    "target_message_size": 0
                },
                "limits": {
                    "system_limit": {
                        "min_memory": 1073741824,
                        "max_memory": 10737418240,
                        "memory_fraction": 0.2,
                        "streams_inbound": 65536,
                        "streams_outbound": 131072,
                        "streams": 262144,
                        "conns_inbound": 256,
                        "conns_outbound": 256,
                        "conns": 1024,
                        "fd": 8192
                    },
                    "transient_limit": {
                        "streams_inbound": 2048,
                        "streams_outbound": 4096,
                        "streams": 4096,
                        "conns_inbound": 256,
                        "conns_outbound": 256,
                        "conns": 512,
                        "fd": 1024
                    }
                },
                "connection_manager": {
                    "high_water": 3000,
                    "low_water": 2000
                }
            },
            "jaeger": {
                "enable_tracing": false,
                "provider_url": "http://localhost:14268/api/traces",
                "sampler_ratio": 1
            },
            "deal": {
                "fail_on_transfer_failure": false,
                "disable": false,
                "verified": true
            },
            "content": {
                "disable_local_adding": false,
                "disable_global_adding": false
            },
            "low_mem": false,
            "disable_filecoin_storage": false,
            "replication": 6,
            "logging": {
                "api_endpoint_logging": true
            }
        },
        "shuttles": [
            {
                "data": {
                    "api_listen": ":3005",
                    "content": {
                        "disable_global_adding": false,
                        "disable_local_adding": false
                    },
                    "data_dir": ".",
                    "database_conn_string": "sqlite=estuary-shuttle.db",
                    "dev": true,
                    "estuary_remote": {
                        "api": "localhost:3004",
                        "auth_token": "SECRET164ae679-****-****-****-1e4aee439883SECRET",
                        "handle": "SHUTTLE0074fd33-****-****-****-a58a554856aeHANDLE"
                    },
                    "hostname": "localhost:3005",
                    "jaeger": {
                        "enable_tracing": false,
                        "provider_url": "http://localhost:14268/api/traces",
                        "sampler_ratio": 1
                    },
                    "logging": {
                        "api_endpoint_logging": true
                    },
                    "no_reload_pin_queue": false,
                    "node": {
                        "announce_addrs": [],
                        "bitswap": {
                            "max_outstanding_bytes_per_peer": 5242880,
                            "target_message_size": 16384
                        },
                        "blockstore": "blocks",
                        "connection_manager": {
                            "high_water": 3000,
                            "low_water": 2000
                        },
                        "datastore_dir": "leveldb",
                        "enable_websocket_listen_addr": false,
                        "hard_flush_write_log": false,
                        "libp2p_key_file": "peer.key",
                        "limits": {
                            "system_limit": {
                                "conns": 1024,
                                "conns_inbound": 256,
                                "conns_outbound": 256,
                                "fd": 8192,
                                "max_memory": 10737418240,
                                "memory_fraction": 0.2,
                                "min_memory": 1073741824,
                                "streams": 262144,
                                "streams_inbound": 65536,
                                "streams_outbound": 131072
                            },
                            "transient_limit": {
                                "conns": 512,
                                "conns_inbound": 256,
                                "conns_outbound": 256,
                                "fd": 1024,
                                "streams": 4096,
                                "streams_inbound": 2048,
                                "streams_outbound": 4096
                            }
                        },
                        "listen_addrs": [
                            "/ip4/0.0.0.0/tcp/6745",
                            "/ip4/0.0.0.0/udp/6746/quic"
                        ],
                        "no_blockstore_cache": false,
                        "no_limiter": true,
                        "wallet_dir": "wallet",
                        "write_log_dir": "",
                        "write_log_truncate": false
                    },
                    "private": false,
                    "staging_data_dir": "staging"
                }
            }
        ]
    }

```
NB: the roots `primary` and `shuttles`

Sample output when accessed from a shuttle instance

```json

{
    "data": {
        "database_conn_string": "sqlite=estuary-shuttle.db",
        "staging_data_dir": "staging",
        "data_dir": ".",
        "api_listen": ":3005",
        "hostname": "localhost:3005",
        "private": false,
        "dev": true,
        "no_reload_pin_queue": false,
        "node": {
            "listen_addrs": [
                "/ip4/0.0.0.0/tcp/6745",
                "/ip4/0.0.0.0/udp/6746/quic"
            ],
            "announce_addrs": [],
            "enable_websocket_listen_addr": false,
            "blockstore": "blocks",
            "write_log_dir": "",
            "hard_flush_write_log": false,
            "write_log_truncate": false,
            "no_blockstore_cache": false,
            "no_limiter": true,
            "libp2p_key_file": "peer.key",
            "datastore_dir": "leveldb",
            "wallet_dir": "wallet",
            "bitswap": {
                "max_outstanding_bytes_per_peer": 5242880,
                "target_message_size": 16384
            },
            "limits": {
                "system_limit": {
                    "min_memory": 1073741824,
                    "max_memory": 10737418240,
                    "memory_fraction": 0.2,
                    "streams_inbound": 65536,
                    "streams_outbound": 131072,
                    "streams": 262144,
                    "conns_inbound": 256,
                    "conns_outbound": 256,
                    "conns": 1024,
                    "fd": 8192
                },
                "transient_limit": {
                    "streams_inbound": 2048,
                    "streams_outbound": 4096,
                    "streams": 4096,
                    "conns_inbound": 256,
                    "conns_outbound": 256,
                    "conns": 512,
                    "fd": 1024
                }
            },
            "connection_manager": {
                "high_water": 3000,
                "low_water": 2000
            }
        },
        "jaeger": {
            "enable_tracing": false,
            "provider_url": "http://localhost:14268/api/traces",
            "sampler_ratio": 1
        },
        "content": {
            "disable_local_adding": false,
            "disable_global_adding": false
        },
        "logging": {
            "api_endpoint_logging": true
        },
        "estuary_remote": {
            "api": "localhost:3004",
            "handle": "SHUTTLE0074fd33-****-****-****-a58a554856aeHANDLE",
            "auth_token": "SECRET164ae679-****-****-****-1e4aee439883SECRET"
        }
    }
}

```
closes https://github.com/application-research/estuary/issues/232

### CODE REVIEW

**Comment by brendalee** [comment]
thanks Lawrence! looks good to me.

**Review by alvin-reyes — APPROVED** [review]
Looks good. Only comment is we need to add the swagger definition for `handleGetSystemConfig`.

**Comment by alvin-reyes** [comment]
Please fix the conflicting file(s).

**Comment by en0ma** [comment]
> Looks good. Only comment is we need to add the swagger definition for `handleGetSystemConfig`.

done

**Pull request merged**
