### PR TITLE
avoid trying to traverse through sector cids in pinned data

### PR DESCRIPTION
**Pull request by whyrusleeping**
This will make it slightly better if we try to pin filecoin state roots

### CODE REVIEW

**Comment by en0ma** [comment]
@whyrusleeping I am just curious to learn more on why this needed

**Comment by en0ma** [comment]
@whyrusleeping I understand now 😄

**Review by en0ma — APPROVED** [review]
LGTM

**Comment by alvin-reyes** [comment]
> @whyrusleeping I am just curious to learn more on why this needed

@whyrusleeping @en0ma Just for my understanding, can you confirm: 

we don’t need to traverse through the sectors cids because its not really part of the file cids (links) and will have additional overhead?

**Comment by en0ma** [comment]
> we don’t need to traverse through the sectors cids because its not really part of the file cids (links) and will have additional overhead?

What I understand is, from a storage client perspective (estuary as a storage client), clients almost don't deal with filecoin state roots (besides piece CID needed for deals, and the blocks are never stored on the client-side). So these roots should not be in the blockstore, If they even get into the blockstore, this PR will make sure they are not traversed - as they wont be anything to travserve

**Review by gmelodie — APPROVED** [review]
LGTM

**Pull request merged**
