### PR TITLE
fix: use the default links per block for importing file

### PR DESCRIPTION
**Pull request by alvin-reyes**
# Changes

I noticed that the dag builder generates a different cid when from IPFS. 

This PR will use the same default number of links per block configuration on the dag builder which will make it par with IPFS/Kubo. 

I have tested it with several files and it works as expected. @en0ma please test this against your files as well.

### CODE REVIEW

**Comment by jlogelin** [comment]
LGTM

**Review by jlogelin — APPROVED** [review]
LGTM

**Comment by en0ma** [comment]
@alvin-reyes It did not work for me

**Comment by gmelodie** [comment]
@alvin-reyes I got both equal and different CIDs. The difference seems to be when the file is larger in size.

**Comment by alvin-reyes** [comment]
I realized that we don’t need to change the way we compute our CIDs since it’ll work either anyway. We encountered a weird behaviour last week where in the CIDs are different from the ones uploaded on api.estuary.tech and on shuttles.

I think @en0ma already fixed this on his commit (e.i revert the logic to dump the content to the blockstore).

**Pull request merged**
