### PR TITLE
properly handle peer addrInfo for pinner

### PR DESCRIPTION
**Pull request by en0ma**

### CODE REVIEW

**Review by snissn — APPROVED** [review]
looks good to me! handling the MultiAddr data types like they're toxic waste

**Comment by anjor** [comment]
I haven't been paying close attention to this, but did this bug always exist? Why are we only seeing it now?

**Review by alvin-reyes — APPROVED** [review]
LGTM

**Comment by en0ma** [comment]
> I haven't been paying close attention to this, but did this bug always exist? Why are we only seeing it now?

So the pinner queue was refactored to be persistent (save pin requests to disk as we receive them), and process them queued pins sequentially. Some pins' payload has peer values which are wonky formats, and because the peer struct is a bit complex (serializing it in its raw form can give unpredictable outcome when deserializing), so when the pinner manager encodes them and tries to decode them, it panics. 

This PR is to make the peer use a simple struct that will be consistent for both encode and decode

**Pull request merged**
