### PR TITLE
changed announce to announce-addr in main

### PR DESCRIPTION
**Pull request by franklovefrank**
https://github.com/application-research/estuary/issues/702

### CODE REVIEW

**Review by gmelodie — APPROVED** [review]

**Review by anjor — CHANGES_REQUESTED** [review]
Fix the build please?

**Comment by franklovefrank** [comment]
any guesses whats causing build to fail? there were only a couple of lines changed..

**Comment by alvin-reyes** [comment]
Hi please pull the new changes from `dev` to your branch and let the build run again.

**Comment by franklovefrank** [comment]
pulled and still failing. from the logs it looks like some of the test files include in build tests are not tests.. i don't know if there's anything i can do about that from my end

**Comment by gmelodie** [comment]
Seems fine, @anjor ?

**Review by neelvirdy — APPROVED** [review]

**Pull request closed without merging**
