### PR TITLE
Pin mgr test

### PR DESCRIPTION
**Pull request by snissn**
this test exposes a bug in the pin manager where if the number of workers > 1 some pins will be lost and never worked on

### CODE REVIEW

**Comment by snissn** [comment]
the number is small though, if there are 1000 pins that should be worked on 996 will get worked on

**Review by jlogelin — DISMISSED** [review]
Awesome, thanks @snissn - looks great!

**Review by en0ma — APPROVED** [review]

**Review by alvin-reyes — DISMISSED** [review]
LGTM. 

I would prefer to use the ginkgo framework but this works. If you have some cycles, please convert this to gingko 

https://github.com/application-research/estuary/blob/unit-tests/tests/unit/handler_content_test.go

**Comment by snissn** [comment]
cool! Definitely can & will convert to ginko in the backlog! Feeling good now about the state of the test and also about the state of the disk based dequeue, checking into the filter/guard branch next

**Comment by snissn** [comment]
btw i pushed a few fixes to this branch so it needs another approval

**Review by alvin-reyes — APPROVED** [review]
LGTM

**Pull request merged**
